# Generated by Django 4.2.9 on 2024-01-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='shorter_content',
            field=models.TextField(blank=True),
        ),
    ]
